<a href="https://colab.research.google.com/github/iam-fern/Generate_addition_4X/blob/main/Generate_addition_4X.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Generating random numbers from a uniform distribution
https://subscription.packtpub.com/book/big_data_and_business_intelligence/9781787125698/12/ch25lvl1sec126/generating-random-numbers-from-a-uniform-distribution

In [1]:
import pandas as pd
import numpy as np
import scipy as sp
import math
import matplotlib.pyplot as plt
from scipy.stats import norm
from numpy.random import normal
import statistics
import statistics as stats
import scipy.stats as ss
from scipy import stats
import scipy.stats as stats
import random
import statsmodels.api as sm
%matplotlib inline
from google.colab import files

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [2]:
sp.random.seed(314157)

In [5]:
n=30
rep=0
#sp.random.seed(314157)
table_data_all=pd.DataFrame({"rep":[]})

for i in range(1000):
    data = pd.DataFrame({"X1" : sp.random.uniform(20, 100, n),
                         "X2" : sp.random.uniform(20, 100, n),
                         "X3" : sp.random.uniform(20, 100, n),
                         "X4" : sp.random.uniform(20, 100, n)})
    table_data = data.copy()
    table_data["e"] = table_data["X2"].apply(lambda X2: np.random.normal(0, math.sqrt(1*((1+X2)**(0)))))

    # ==========================================

    # table_data = data_new.copy()


    table_data["Y"] = 10 + table_data["X1"] + table_data["X2"] + table_data["X3"] + table_data["X4"] + table_data["e"]
    
    table_data=table_data.reset_index(drop=True).reset_index()
    table_data["rep"]=rep
    new_data = table_data.copy()

    # ==========================================
    x = new_data[["X1", "X2", "X3", "X4"]]
    y = new_data["Y"]
    x = sm.add_constant(x)
    model = sm.OLS(y, x).fit()
    y_pred = model.predict(x)

    df = pd.DataFrame({"Actual": y, "Predicted": y_pred})

    table_data_new = pd.DataFrame({"x1"    : new_data["X1"],
                                   "x2"    : new_data["X2"],
                                   "x3"    : new_data["X3"],
                                   "x4"    : new_data["X4"],
                                   "e"     : new_data["e"],
                                   "Y"     : df["Actual"],
                                   "y_hat" : df["Predicted"]})
    table_data_new["e_hat"] = table_data_new["Y"] - table_data_new["y_hat"]
    table_data_new["rep"] = rep
    table_data_new = table_data_new.reset_index()
    table_data_new
    # ==========================================
    table_data_all=pd.concat([table_data_all,table_data_new],axis=0,ignore_index=True,sort=False)
    rep+=1
    if rep==1000:
      break
table_data_all=table_data_all.set_index(["rep", "index"])
table_data_all

/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/tsatools.py:117: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)

                    x1         x2         x3         x4         e           Y  \
rep   index
0.0   0.0    51.273073  71.031970  21.689647  20.968026 -0.260079  174.702637
      1.0    58.216419  35.994788  45.726878  74.567764 -0.454202  224.051646
      2.0    94.840730  87.564307  45.510430  67.821876 -1.474181  304.263161
      3.0    69.199043  56.239562  60.438241  38.835817  0.757637  235.470301
      4.0    83.715065  29.287155  74.389530  79.364469  0.508114  277.264333
...                ...        ...        ...        ...       ...         ...
999.0 25.0   83.751775  68.993108  84.311797  84.152295  1.559675  332.768650
      26.0   77.300536  41.044830  45.884739  73.518350  0.058904  247.807360
      27.0   54.891845  88.225996  32.384490  53.651149  0.630723  239.784202
      28.0   74.191576  71.378633  95.617934  58.469024 -0.028583  309.628583
      29.0   25.649679  67.240971  63.005928  79.448139  0.884310  246.229027

                  y_hat     e_hat
rep   index
0.0   0.0    175.301483 -0.598845
      1.0    224.284062 -0.232416
      2.0    305.725257 -1.462096
      3.0    234.615743  0.854558
      4.0    276.299801  0.964531
...                 ...       ...
999.0 25.0   330.976327  1.792323
      26.0   247.682056  0.125304
      27.0   238.926071  0.858131
      28.0   309.351294  0.277289
      29.0   245.819378  0.409649

[30000 rows x 8 columns]

In [4]:
table_data_all.to_csv('data_add_delta_0_n30.csv')
files.download('data_add_delta_0_n30.csv')